services:
  - type: web
    name: sufuf-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
    plan: free