services:
  - type: web
    name: sufuf-websocket
    env: node
    region: frankfurt
    buildCommand: |
      npm install typescript -g
      npm install
      tsc --project tsconfig.json
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    cors:
      allowedOrigins:
        - https://*.vercel.app
    autoDeploy: true
    numInstances: 1